### PR TITLE
Flexible find

### PR DESCRIPTION
**Pull request by ChenXy128**

### CODE REVIEW

**Comment by HongRay** [comment]
Good code, i like how you implemented Optional into your solution and how u added javadocs for almost every method and class you created!

**Comment by Xuyan0518** [comment]
Looks good to me. I like the way you implemented this feature. This find feature is useful for our product.

**Comment by Cedricaca** [comment]
Very nice job, will be a fine addition to our product

**Comment by NusMinato** [comment]
Good job bro! I like your coding style.

**Pull request merged**
