### PR TITLE
Branch add command

### PR DESCRIPTION
**Pull request by Xuyan0518**
Implement the addCommand feature to add a new person to the application.

### CODE REVIEW

**Comment by Cedricaca** [comment]
Looks good, I like how you coded your part, very ingenious

**Review by Cedricaca — COMMENTED** [review]
LGTM

**Review by NusMinato — COMMENTED** [review]
LGTM. Very clean code, easy to understand.

**Review by HongRay — COMMENTED** [review]
Good code. Amazing job!

**Comment by ChenXy128** [comment]
LGTM! Just need some JavaDoc

**Pull request merged**
